# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "opscode-centos-7.1"
  # master server which execute ansible2yaml and yaml2excel
  config.vm.define "master" do |node|
    node.vm.hostname = "master"
    node.vm.network :private_network, ip: "192.168.33.181"
    node.vm.synced_folder "..", "/vagrant"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    # ansible provision
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision/site.yml"
    end
  end
  # node server which is applyed ansible
  config.vm.define "node1" do |node|
    node.vm.hostname = "node1"
    node.vm.network :private_network, ip: "192.168.33.10"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
  end
  config.vm.define "node2" do |node|
    node.vm.hostname = "node2"
    node.vm.network :private_network, ip: "192.168.33.11"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
 end
end
